export const gameTitles: string[] = [
    'Fortnite',
    'Minecraft',
    'Among Us',
    'Call of Duty: Warzone',
    'Apex Legends',
    'PlayerUnknown\'s Battlegrounds (PUBG)',
    'Overwatch',
    'Rocket League',
    'League of Legends',
    'Dota 2',
    'Rainbow Six Siege',
    'Counter-Strike: Global Offensive (CS:GO)',
    'Valorant',
    'GTA Online',
    'FIFA',
    'NBA 2K',
    'World of Warcraft',
    'Destiny 2',
    'Sea of Thieves',
    'Monster Hunter: World',
    'Splatoon 2',
    'Super Smash Bros. Ultimate',
    'Mario Kart 8 Deluxe',
    'Madden NFL',
    'Team Fortress 2',
];
