export const multiplayerGameTitles = {
    Top25: [
        'Fortnite',
        'Minecraft',
        'Among Us',
        'Call of Duty: Warzone',
        'Apex Legends',
        'PlayerUnknown\'s Battlegrounds (PUBG)',
        'Overwatch',
        'Rocket League',
        'League of Legends',
        'Dota 2',
        'Rainbow Six Siege',
        'CS:GO',
        'Valorant',
        'GTA Online',
        'GTA V',
        'FIFA',
        'NBA 2K',
        'World of Warcraft',
        'Destiny 2',
        'Sea of Thieves',
        'Monster Hunter: World',
        'Splatoon 2',
        'Super Smash Bros. Ultimate',
        'Mario Kart 8 Deluxe',
        'Team Fortress 2',
    ],
    A: [
        "Among Us",
        "Apex Legends",
        "ARK: Survival Evolved",
        "Arma 3",
        "Assassin's Creed Valhalla",
        "Assetto Corsa",
        "Avengers",
        "Age of Empires II: Definitive Edition",
        "Anthem",
        "Animal Crossing: New Horizons",
        "Astroneer",
        "Anno 1800",
        "Alien: Isolation",
        "Adventures of Mana",
        "Amnesia: A Machine for Pigs",
        "A Way Out",
        "Albion Online",
        "Artifact",
        "Ace Combat 7: Skies Unknown",
        "AirMech Strike",
        "Absolver",
        "Arizona Sunshine",
        "Ashen",
        "Attack on Titan 2",
        "Ashes of Creation"
    ],
    B: [
        "Battlefield 2042",
        "Brawl Stars",
        "Borderlands 3",
        "Black Desert Online",
        "Baldur's Gate III",
        "Battlefield V",
        "BioShock 2 Remastered",
        "Brawlhalla",
        "Blade & Soul",
        "Bloons TD 6",
        "Bloodborne",
        "Burnout Paradise Remastered",
        "Beyond: Two Souls",
    ],
    C: [
        "Call of Duty: Warzone",
        "Call of Duty: Warzone 2",
        "Counter-Strike: Global Offensive",
        "CSGO",
        "CS2",
        "Control",
        "Conan Exiles",
        "Crash Team Racing Nitro-Fueled",
        "Crysis Remastered",
        "Cuphead",
        "Cities: Skylines",
        "Code Vein",
        "Call of Duty: Modern Warfare",
        "Call of Duty: Modern Warfare II",
        "Call of Duty: Black Ops Cold War",
        "Call of Duty: Black Ops 4",
        "Call of Duty: Black Ops III",
        "Civilization VI",
        "Civilization V",
        "Civilization IV",
        "Command & Conquer Remastered Collection",
        "Castle Crashers Remastered",
        "Conqueror's Blade",
        "Carrion",
    ],
    D: [
        "Dead by Daylight",
        "Destiny 2",
        "Divinity: Original Sin 2",
        "Deep Rock Galactic",
        "Dota 2",
        "Dauntless",
        "Dead Space 2",
        "Dying Light",
        "Dying Light 2",
        "Don't Starve Together",
        "Dragon Ball FighterZ",
        "Diablo III",
        "Diablo IV",
        "Disco Elysium",
        "Darkest Dungeon",
        "Dishonored 2",
        "Darksiders III",
        "DayZ",
        "Dead Island",
        "Deus Ex: Mankind Divided",
        "Dead Rising 4"
    ],
    E: [
        "Elden Ring",
        "Escape from Tarkov",
        "Elder Scrolls Online",
        "Elite Dangerous",
        "Eve Online",
        "Eco",
        "Empire of Sin",
        "Enter the Gungeon",
        "Euro Truck Simulator 2",
        "Europa Universalis IV",
        "Expeditions: Viking",
        "Earth Defense Force 5",
        "Everspace",
        "Endless Space 2",
        "Empyrion - Galactic Survival",
        "Elite Dangerous: Odyssey",
        "Epic Battle Fantasy 5",
        "Endzone - A World Apart",
        "Eternity: The Last Unicorn",
        "El Hijo - A Wild West Tale",
        "Endless Legend",
        "Exanima",
    ],
    F: [
        "Fall Guys",
        "Fortnite",
        "FIFA 22",
        "Far Cry 6",
        "For Honor",
        "Factorio",
        "Football Manager 2023",
        "Friday Night Funkin'",
        "Fallout 76",
        "Farming Simulator 19",
        "Fuser",
        "Final Fantasy XIV",
        "Final Fantasy X/X-2 HD Remaster",
        "Final Fantasy VIII Remastered",
        "Final Fantasy XII: The Zodiac Age",
        "Final Fantasy XIII",
        "Final Fantasy XV",
        "Final Fantasy XVI",
        "Final Fantasy",
        "FIFA 21",
        "Fallout 4",
        "Forza Horizon 5"
    ],
    G: [
        "Grand Theft Auto V",
        "Genshin Impact",
        "Ghost of Tsushima",
        "God of War",
        "Garry's Mod",
        "Grounded",
        "Ghostrunner",
        "GreedFall",
        "Gothic II: Gold Edition",
        "Green Hell",
        "Grim Dawn",
        "GTFO",
        "GRID",
        "Golf With Your Friends",
        "Godfall",
        "Gris",
        "Generation Zero",
        "Gunfire Reborn",
        "Gears 5",
        "Geometry Dash",
        "Generation of Chaos",
        "God Eater 3",
        "Grisaia Phantom Trigger Vol.5",
        "Gunfire Reborn",
        "Gears of War 4"
    ],
    H: [
        "Hades",
        "Halo Infinite",
        "Hunt: Showdown",
        "Hollow Knight",
        "Heroes of the Storm",
        "Half-Life: Alyx",
        "Human: Fall Flat",
        "Horizon Zero Dawn",
        "Hotline Miami",
        "Hearthstone",
        "Halo: The Master Chief Collection",
        "Hades",
        "Hyper Scape",
        "Hytale",
        "Hogwarts Legacy",
        "Heavy Rain",
        "Hotline Miami 2: Wrong Number",
        "Hunt: Showdown",
        "Hitman 3",
        "House Flipper",
        "Hellblade: Senua's Sacrifice",
        "Helldivers",
        "House Party",
        "Hand Simulator",
        "Hardspace: Shipbreaker"
    ],
    I: [
        "It Takes Two",
        "Injustice 2",
        "Insurgency: Sandstorm",
        "Inscription",
        "Inside",
        "Iron Harvest",
        "Immortals Fenyx Rising",
        "Indivisible",
        "Infra",
        "Icarus",
        "Irony Curtain: From Matryoshka with Love",
        "Into the Breach",
        "Iron Man VR",
        "I Am Fish",
        "Insurgency",
        "Injustice: Gods Among Us Ultimate Edition",
        "Ion Fury",
        "Injustice: Gods Among Us",
        "Iratus: Lord of the Dead",
        "Infestation: The New Z",
        "Injustice 2",
        "Infliction",
        "Inferno Climber",
        "It Lurks Below",
        "Insane Robots"
    ],
    J: [
        "Just Chatting",
        "Jump Force",
        "Jurassic World Evolution",
        "Jackbox",
        "Jump King",
        "Journey",
        "Jalopy",
        "Jurassic World Evolution: Return to Jurassic Park",
        "Just Cause 4",
        "JUMP FORCE",
        "Just Cause 3",
        "Just Dance 2022",
        "Jurassic World Evolution - Deluxe DLC",
        "Journey to the Savage Planet",
        "Joggernauts",
        "Jeopardy!",
        "Jagged Alliance 2 - Wildfire",
        "John Wick Hex"
    ],
    K: [
        "Knockout City",
        "Kena: Bridge of Spirits",
        "Kingdom Hearts III",
        "Kerbal Space Program",
        "Killing Floor 2",
        "Katana ZERO",
        "Katamari Damacy REROLL",
        "Kentucky Route Zero: TV Edition",
        "Knights and Bikes",
        "KartRider: Drift",
        "Killer Instinct",
        "Katana ZERO",
        "Kenshi",
        "Kingdoms of Amalur: Re-Reckoning",
        "Killing Floor",
        "Kingdom Come: Deliverance",
        "Kine",
        "Kane & Lynch 2: Dog Days",
        "Killer is Dead - Nightmare Edition",
        "Kunai",
        "Kynseed",
        "Kao the Kangaroo: Round 2",
        "Kingdom Under Fire 2",
        "Kingdom Hearts HD 1.5 + 2.5 Remix"
    ],
    L: [
        "League of Legends",
        "Left 4 Dead 2",
        "L.A. Noire",
        "Little Nightmares",
        "Luigi's Mansion 3",
        "Life is Strange",
        "Layers of Fear",
        "Lego Star Wars: The Skywalker Saga",
        "Lethal League Blaze",
        "Lego Marvel Super Heroes 2",
        "Lost Ark",
        "Little Nightmares II",
        "Lego DC Super-Villains",
        "Life is Strange: Before the Storm",
        "Lust from Beyond",
        "Little Witch Academia: Chamber of Time",
        "Life is Strange 2",
        "Lust for Darkness",
        "Lords of the Fallen",
        "Lonely Mountains: Downhill",
        "Last Year: The Nightmare",
        "Little Nightmares - Secrets of The Maw Expansion Pass",
        "L.A. Noire: The VR Case Files",
        "LEGO Worlds",
        "LEGO The Incredibles"
    ],
    M: [
        "Minecraft",
        "Monster Hunter: World",
        "Mortal Kombat 11",
        "Mass Effect",
        "Metro Exodus",
        "MIR4",
        "Maple Story",
        "Marvel's Avengers",
        "Middle-earth: Shadow of War",
        "Madden NFL 22",
        "Mortal Kombat X",
        "My Time at Portia",
        "Monster Hunter Rise",
        "Mordhau",
    ],
    N: [
        "Naraka: Bladepoint",
        "Need for Speed Heat",
        "No Man's Sky",
        "NBA 2K22",
        "NBA 2K23",
        "Nioh 2",
        "NBA 2K21",
        "Nidhogg 2",
        "Nexomon: Extinction",
        "New World",
        "NBA 2K Playgrounds 2",
        "Nier: Automata - Game of the YoRHa Edition",
        "Noita",
        "NARUTO SHIPPUDEN",
        "Nex Machina",
    ],
    O: [
        "Overwatch",
        "Overwatch 2",
        "Outlast 2",
        "Outriders",
        "Outer Wilds",
        "One Piece: Pirate Warriors 4",
        "Outlast",
        "Orcs Must Die! 3",
        "Oxygen Not Included",
        "ONE PUNCH MAN: A HERO NOBODY KNOWS",
        "Ori and the Blind Forest",
        "OBSERVER",
        "OCTOPATH TRAVELER",
        "One Piece: World Seeker",
        "Overcooked! 2",
        "Outward",
        "Omensight",
        "ONE PIECE: PIRATE WARRIORS 3",
        "Oxenfree",
        "Out of the Park Baseball 21",
        "One Finger Death Punch 2",
        "ONE PIECE BURNING BLOOD",
        "Onimusha: Warlords",
        "Ori and the Blind Forest: Definitive Edition",
        "Othercide"
    ],
    P: [
        "PlayerUnknown's Battlegrounds",
        "Portal 2",
        "Phasmophobia",
        "Pathfinder: Wrath of the Righteous",
        "Pummel Party",
        "Papers, Please",
        "Project Winter",
        "Phantom Abyss",
        "Path of Exile",
        "PAYDAY 2",
        "Planet Zoo",
        "Pummel Party",
        "Prison Architect",
        "Paladins",
        "PUBG: BATTLEGROUNDS",
        "Pillars of Eternity II: Deadfire",
        "Project Zomboid",
        "Prison Architect",
        "Phantom Breaker: Battle Grounds",
        "Plants vs. Zombies: Battle for Neighborville",
        "Plants vs. Zombies: Garden Warfare 2"
    ],
    Q: [
        "Quiplash",
        "Quake Champions",
        "Quantum League",
        "Quake Live",
        "Quake III Arena",
        "Quantum Break",
        "QuiVr",
        "Quarantine",
        "Quantum Conundrum",
        "Q.U.B.E. 2",
        "Quest Hunter",
        "QUBE: Director's Cut",
        "Q.U.B.E.",
        "Quern - Undying Thoughts",
        "Queen's Quest 2: Stories of Forgotten Past",
        "Queen's Quest 3: The End of Dawn",
        "Quantum Replica",
        "Quest for Glory Collection",
        "Queen's Quest 4: Sacred Truce",
        "Quest of Dungeons",
        "Queen's Wish: The Conqueror",
        "Quantum Error",
        "Qajary Cat",
        "Quattro Arcade",
        "Q-YO Blaster"
    ],
    R: [
        "Rocket League",
        "Red Dead Redemption 2",
        "Rust",
        "Rainbow Six Siege",
        "Risk of Rain 2",
        "Rogue Company",
        "Raft",
        "Remnant: From the Ashes",
        "RimWorld",
        "Reigns",
        "Rocket Arena",
        "Resident Evil",
        "Remnant: From the Ashes - Swamps of Corsus",
        "Rivals of Aether",
        "Rage 2"
    ],
    S: [
        "Sea of Thieves",
        "Stardew Valley",
        "Stellaris",
        "Super Smash Bros. Ultimate",
        "Satisfactory",
        "Squad",
        "Slay the Spire",
        "Star Wars Jedi: Fallen Order",
        "Sid Meier's Civilization VI",
        "Sid Meier's Civilization V",
        "Spiritfarer",
        "Subnautica",
        "Secret Neighbor",
        "Super Meat Boy Forever",
        "Spelunky 2",
    ],
    T: [
        "Terraria",
        "The Witcher 3: Wild Hunt",
        "Tom Clancy's The Division 2",
        "Team Fortress 2",
        "Total War: Warhammer II",
        "Titanfall 2",
        "Tales of Arise",
        "The Elder Scrolls Online",
        "The Forest",
        "The Binding of Isaac: Rebirth",
        "The Sims 4",
        "The Elder Scrolls V: Skyrim",
        "Torchlight II",
        "Two Point Hospital",
        "The Surge 2",
        "The Long Dark",
        "Total War: WARHAMMER",
        "The Escapists 2",
        "The Evil Within 2",
    ],
    U: [
        "Untitled Goose Game",
        "Unrailed!",
        "Unturned",
        "Unreal Tournament",
        "Unavowed",
        "Ultimate Marvel vs. Capcom 3",
        "Ultra Street Fighter IV",
        "Unheard",
        "Underworld Ascendant",
        "Uplink",
        "Undead Horde",
        "Ultimate Fishing Simulator",
        "Ultimate Marvel vs. Capcom 3"
    ],
    V: [
        "Valorant",
        "Valheim",
        "Vampyr",
        "Valley",
        "Vermintide 2",
        "Viking Warriors",
        "VRChat",
    ],
    W: [
        "Warthunder",
        "Warframe",
        "World of Warcraft",
        "Wolcen: Lords of Mayhem",
        "World of Tanks",
        "Witch It",
        "Wizard101",
        "War for the Overworld",
        "War of Rights",
        "World War Z",
        "Warhammer 40,000",
        "WWE",
    ],
    X: [
        "XCOM 2",
        "Xenoblade Chronicles",
        "Xenoblade Chronicles 2",
        "XCOM",
        "X-Morph: Defense",
        "Xenonauts 2",
    ],
    Y: [
        "Yakuza",
        "Yakuza 2",
        "Yakuza 1&2 HD Edition",
        "Yakuza 3",
        "Yakuza 3 Remastered",
        "Yakuza 4",
        "Yakuza 4 Remastered",
        "Yakuza 5",
        "Yakuza 5 Remastered",
        "Yakuza 6: The Song of Life",
        "Yakuza: Dead Souls",
        "Yakuza Kiwami",
        "Yakuza Kiwami 2",
        "Yakuza: Like a Dragon",
    ],
    Z: [
        "Zup! Zero",
        "Zup! 2",
        "Zup! 3",
        "Zup! 4",
        "Zup! 5",
        "Zup! 6",
        "Zup! 7",
        "Zombie Army Trilogy",
        "Zombie Army 4: Dead War",
        "Zuma Deluxe",
        "Ziggurat",
        "Zeno Clash",
    ]
};
