// via https://www.ge.com/digital/documentation/meridium/V36160/Help/Master/Subsystems/AssetPortal/Content/Time_Zone_Mappings.htm
const timezonesNegative: Record<string, string> = {
    'Dateline Standard Time': '12',
    'UTC-11': '-11',
    'Hawaiian Standard Time': '-10',
    'Alaskan Standard Time': '-9',
    'Pacific Standard Time (US & Canada)': '-8',
    'Mountain Standard Time (US & Canada)': '-7',
    'Central Standard Time': '-6',
    'Eastern Standard Time': '-5',
    'Venezuelan Standard Time': '-4:30',
    'Atlantic Standard Time': '-04',
    'Newfoundland Standard Time': '-3:30',
    'E. South America Standard Time': '-3',
    'Mid-Atlantic Standard Time': '-2',
    'Carpe Verde, Azores Standard Time': '-1',
    'Coordinated Universal Time': 'UTC',
} as const;

// const timezonesDaylight: Record<string, string> = {
//     'Hawaiian Standard Time': '-10',
//     'Hawaiian Daylight Time (Aleutian Islands)': '-9',
//     'Alaskan Daylight Time': '-8',
//     'Pacific Daylight Time (US & Canada)': '-7',
//     'Mountain Daylight Time (US & Canada)': '-6',
//     'Central Daylight Time': '-5',
//     'Eastern Daylight Time': '-4',
// } as const;

const timezonesPositive: Record<string, string> = {
    'Coordinated Universal Time': 'UTC',
    'Central Europe Standard Time': '+1',
    'Middle East Standard Time': '+2',
    'Arabic Standard Time': '+3',
    'Iran Standard Time': '+3:30',
    'Russian Standard Time': '+4',
    'Afghanistan Standard Time': '+4:30',
    'West Asia Standard Time': '+5',
    'India Standard Time': '+5:30',
    'Nepal Standard Time': '+5:45',
    'Myanmar Standard Time': '+6:30',
    'Asia Central Standard Time': '+6',
    'Asia SE Standard Time': '+7',
    'Asia N Standard Time': '+8',
    'Asia NE Standard Time': '+9',
    'AUS Central Standard Time': '+9:30',
    'AUS Eastern Standard Time': '+10',
    'Central Pacific Standard Time': '+11',
    'New Zealand Standard Time': '+12',
    'Samoa Standard Time': '+13',
} as const;

const abbreviations = {
    'Dateline Standard Time': 'DST',
    'UTC-11': 'U',
    'Hawaiian Standard Time': 'HST',
    'Alaskan Standard Time': 'AKST',
    'Pacific Standard Time (US & Canada)': 'PST',
    'Mountain Standard Time (US & Canada)': 'MST',
    'Central Standard Time': 'CST',
    'Eastern Standard Time': 'EST',
    'Venezuelan Standard Time': 'VST',
    'Atlantic Standard Time': 'AST',
    'Newfoundland Standard Time': 'NST',
    'E. South America Standard Time': 'ESAST',
    'Mid-Atlantic Standard Time': 'MST',
    'Carpe Verde, Azores Standard Time': 'CVST',
    'Coordinated Universal Time': 'CUT',
    'Central Europe Standard Time': 'CEST',
    'Middle East Standard Time': 'MEST',
    'Arabic Standard Time': 'AST',
    'Iran Standard Time': 'IST',
    'Russian Standard Time': 'RST',
    'Afghanistan Standard Time': 'AST',
    'West Asia Standard Time': 'WAST',
    'India Standard Time': 'IST',
    'Nepal Standard Time': 'NST',
    'Myanmar Standard Time': 'MST',
    'Asia Central Standard Time': 'CAST',
    'Asia SE Standard Time': 'SAST',
    'Asia N Standard Time': 'NCAST',
    'Asia NE Standard Time': 'NAST',
    'AUS Central Standard Time': 'ACST',
    'AUS Eastern Standard Time': 'EAST',
    'Central Pacific Standard Time': 'CPST',
    'New Zealand Standard Time': 'NZST',
    'Samoa Standard Time': 'SST',
}
export {timezonesNegative, timezonesPositive, abbreviations};